### ISSUE TITLE
Fix error for recurring donors who want to edit their information

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#23] opened 2015-03-23 20:00 UTC
This might be a task for @mmmavis (?)
cc: @quakpac 

We need to check the URLs provided on recurring donation pages to make sure donors are seeing the correct links.

Email conversation for reference:

Your request (#32397) has been updated.

To review the status of the request and add additional comments, follow the link below:
http://bsd.zendesk.com/requests/32397

You can also add a comment by replying to this email.

Seth Reznik, Mar 23, 15:54:

Andrea, the content of the search page can be edited here:

https://sendto.mozilla.org/utils/blue_dictionary/admin/section.php?component=modules/contribution&section=Recurring%20Contribution%20Search%20Form

and the view page here:

https://sendto.mozilla.org/utils/blue_dictionary/admin/section.php?component=modules/contribution&section=Recurring%20Contribution%20View%20Page

we can also change the wrapper that is used on those pages, but its something we have to do on the back end, so let me know if you want me to do that.

The one outlier here is that when a user goes to edit their page, it will use the wrapper of the page that they made their initial donation on, which is where I think the problem is.

Andrea Wood, Mar 23, 15:49:

Seth, where in the BSD dashboards do I review / control the content on these pages?

---

Andrea Wood

Director, Digital Organizing + Fundraising
Mozilla

[v] +1 510-922-0181

@valiant

Seth Reznik, Mar 23, 15:31:

Andrea, the URL seems correct to me, I am guessing that the issue is with the front end CSS/JS that the page is using.

Andrea Wood, Mar 23, 15:29:

Yes, that makes sense, but the link people are receiving appears to be broken according to the user. Can you confirm or let me know if the URL something we need to fix on our end?

---

Andrea Wood

Director, Digital Organizing + Fundraising
Mozilla

[v] +1 510-922-0181

@valiant

Seth Reznik, Mar 23, 15:02:

Andrea, the way that this works is we will send the link in that email if your contribution fails. You can also go to the site at:

https://sendto.mozilla.org/page/recurring/find

and plug in your details directly.

When you find the contribution that you are looking for, you can click the button to edit your settings.

You will then be taken to a form, which matches up to the form that you submitted your initial donation on, to update your payment details.

Does that help clarify?

Andrea Wood, Mar 23, 14:56:

Hi there, I need help understanding what users are seeing when they wish to update their credit card information for recurring donations. See the exchange below. I don't even know what link they are accessing and how they access that link (which is apparently broken).

David Hurman david.hurman at btinternet.com (mailto:askjoin%40mozilla.org?Subject=Re:%20Re%3A%20AskJoin%20Regular%20Donation%20to%20Mozilla%20Foundation.&In-Reply-To=%3C550c1f5d.27a2420a.3f33.ffffa601SMTPIN_ADDED_BROKEN%40mx.google.com%3E)
Fri Mar 20 13:23:43 UTC 2015

Hello,     I have been donating $5.00 per month, but my Debit Card has been updated and you can no longer collect the payment.  Your page for amending the Card Details is broken, once I click the Option to Edit. The subsequent page flashes up some sort of form and then follows with a heading, but no boxes to fill in. I have tried Firefox, IE & Google Chrome with the same result.  Please can you assist in correcting this, so that I can continue to support you?     Kind regards  David Hurman (UK Resident)

**Comment by davidascher** [comment] 2015-03-23 20:01
mavis is on PTO. cc @simonwex

**Comment by simonwex** [comment] 2015-03-27 23:31
I can't seem to log in to BSD at the moment. @ScottDowne could you help me look into this Monday morning?

**Comment by ScottDowne** [comment] 2015-03-27 23:55
Yeah, I am having trouble logging in too. I think I have the wrong sign in link?

Nvm, found it.

**Comment by ScottDowne** [comment] 2015-03-28 02:40
I made a monthly donation and a few things come to mind.
1. We send no info about it being monthly and no info on how to cancel it.
2. So I googled it, and got "http://www-archive.mozilla.org/foundation/donate_faq.html#monthly" which is only instructions for paypal but we don't really communicate that paypal and bsd are not the same type of monthly donation, so the user might think they need to use paypal somehow.

This causes confusion which becomes miscommunication between us, or possibly even user error when the user tries to remove a bsd donation via paypal (Hint: it doesn't work ;) )

I was able to cancel without issue using "https://sendto.mozilla.org/page/recurring/find", however, edit took me to an empty page.

Some of this is obviously broken and should be fixed. I'm not convinced we should stop there, but it's a start.
- [ ] Communicate removal of monthly BSD donations through acceptable channels.
- [ ] Fix edit page.

**Comment by ScottDowne** [comment] 2015-03-28 03:56
Edit not working has something to do with the code on this page "https://sendto.mozilla.org/page/recurring/edit/" <-- that won't work if you didn't get there via "https://sendto.mozilla.org/page/recurring/find"

I cannot seem to find those pages anywhere in BSD to start to fix what's wrong.

There is a JS error "TypeError: $theForm.parsley(...) is undefined" which makes me think it's using our main form wrapper, but doesn't have any of the context in page. Probably the cause.

**Comment by ScottDowne** [comment] 2015-03-28 04:27
After doing my debugging and going back and reading the initial comment, it makes more sense now.

It looks like it is a shared wrapper: "The one outlier here is that when a user goes to edit their page, it will use the wrapper of the page that they made their initial donation on, which is where I think the problem is"

That is totally it. We could just, in the wrapper, ensure we check that "$theForm.parsley(...)" is defined before we use it.

**Comment by ScottDowne** [comment] 2015-03-28 04:31
It doesn't look like I have access to either of these links:

https://sendto.mozilla.org/utils/blue_dictionary/admin/section.php?component=modules/contribution&section=Recurring%20Contribution%20Search%20Form

https://sendto.mozilla.org/utils/blue_dictionary/admin/section.php?component=modules/contribution&section=Recurring%20Contribution%20View%20Page

**Comment by simonwex** [comment] 2015-03-28 07:08
@jdotpz does your account have different permissions?

**Comment by jdotpz** [comment] 2015-03-28 14:20
It would seem so, as I'm able to access both of those links.

![screen shot 2015-03-28 at 9 19 53 am](https://cloud.githubusercontent.com/assets/1373628/6881398/ae4f1088-d52b-11e4-993a-8ab560002df8.JPG)
![screen shot 2015-03-28 at 9 19 43 am](https://cloud.githubusercontent.com/assets/1373628/6881396/adaa2640-d52b-11e4-9a25-64639edf22b3.JPG)

**Comment by valianttry** [comment] 2015-03-30 22:07
@ScottDowne True there is a lot wrong with the monthly donor pages and infrastructure. I was prioritizing the most egregious things (broken links) now, but the rest are not P1s. There are other issues related to fundraising / movement building that I think are higher priority, relatively speaking.

**Comment by ScottDowne** [comment] 2015-04-07 01:54
I was testing things in this test page: https://sendto.mozilla.org/page/contribute/seq-test-page

I got it kinda working with the edit page for donations made in the above test page. All the js errors are gone, but the css is still pretty busted.

From the first comment in this bug "we can also change the wrapper that is used on those pages, but its something we have to do on the back end, so let me know if you want me to do that."

Yes, we should do that. That's the not hacky fix.

**Comment by ScottDowne** [comment] 2015-04-09 22:45
@valianttry I think we should request that "we can also change the wrapper that is used on those pages, but its something we have to do on the back end, so let me know if you want me to do that." happens.

**Comment by edrushka** [comment] 2015-04-24 18:29
@valianttry pinging you on this one. I believe the next step is for you to contact BSD to make this request. Please let us know when that's happened.

**Comment by ScottDowne** [comment] 2015-05-07 00:29
After opening a BSD ticket and going back and forth a bit with Seth, I think we have a fix: https://github.com/mozilla/bsd-forms-and-wrappers/pull/122

The edit recurring page is not pretty, at all. Been warned...

![notpetty](https://cloud.githubusercontent.com/assets/197334/7506457/24c5deba-f42e-11e4-9864-7b6c681f146a.png)

A basic pass to clean that up would do wonders. Should we clean it up before shipping or let people use it as is? Current state doesn't work at all.

How I fixed this you need to understand the problem.

BSD shares the below page content with all pages associated with the donation page, so far, this is the recurring donation edit page. The wrapper is also shared.

We had js in the below page that was expecting html created in the above page.

The edit page however doesn't include the above page content, just the below. So we shouldn't be shipping them as separate content, we should have it as one. my patch also makes the input boxes big enough to see the content.

R?

**Comment by ScottDowne** [comment] 2015-05-07 00:31
Oh, I have an example page live with my code here: https://sendto.mozilla.org/page/contribute/seq-test-page

If you make a recurring donation there, and go to https://sendto.mozilla.org/page/recurring/find you'll be able to find your new recurring donation and edit it. If you do that using the stable donation page you'll get an empty page instead of the edit page.

Let me know if you have more questions.

**Comment by valianttry** [comment] 2015-05-07 01:31
Sorry i must be daft. I'm super confused now. :frowning: Maybe we should chat tomorrow so I'm clear? I'm open most of the day.

**Comment by ScottDowne** [comment] 2015-05-07 02:22
@valianttry Yeah let's connect.

**Comment by ScottDowne** [comment] 2015-05-07 21:29
Updated the styles:

![edit](https://cloud.githubusercontent.com/assets/197334/7526446/908e0ec2-f4df-11e4-8932-583bcd31ea68.png)

**Comment by ScottDowne** [comment] 2015-05-07 21:42
@alicoding has context for this so throwing it to him for review. Mavis you can feel free to take a look too, cannot hurt :)

**Comment by valianttry** [comment] 2015-05-07 21:55
it's so.... beautiful :cry:

**Comment by ScottDowne** [comment] 2015-05-11 21:40
This was shipped, closing.

**Closed as completed by ScottDowne** 2015-05-11 21:40 UTC
Labels: needs-dev
