### ISSUE TITLE
Update advocacy site with NN win graphic

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#18] opened 2015-02-26 19:16 UTC
RACI

Driver: @edrushka
Dev: @wex - PLEASE ASSIGN
Design: minimal design needed @iamjessklein 
Copy: @kevzawacki
Decision-maker: @valianttry 
Consulted: @HPaulJohnson @DaveSteer @melechuga

We need to update https://advocacy.mozilla.org/ with the results of the NN decision:

Replace the white 'Protect Net Neutrality' banner (all text, logo and CTA buttons) with:

1) A banner featuring the red image of the capitol building with fireworks from Issue #16 (banner background colour can be red)
2) Headline: On February 26, the FCC voted to protect net neutrality
Subheader: You made this victory possible and helped protect the world's most valuable public resource" 
3) 'Read more' text Link to Mitchell's blog: https://blog.mozilla.org/blog/2015/02/25/a-major-victory-for-the-open-web/

@kevzawacki can you please tweak the copy as needed and then pass off to @iamjessklein for a quick mock-up?

**Comment by HPaulJohnson** [comment] 2015-02-26 19:39
Link for #3 is broken. Should be this one https://blog.mozilla.org/blog/2015/02/26/a-major-victory-for-the-open-web-2/

**Comment by KevZawacki** [comment] 2015-02-26 20:54
Updated copy (minor edits to Erika's work):

Headline: On February 26, the FCC voted to protect net neutrality

Subhead: You made this victory possible! Thank you for helping preserve the world's most valuable public resource.

cc @iamjessklein

**Comment by iamjessklein** [comment] 2015-03-02 18:11
Just saw this now, will pull a mockup together.

**Comment by edrushka** [comment] 2015-03-02 19:16
Thanks, @iamjessklein! @cassiemc can you confirm that Jess is the designer on call for advocacy stuff for this heartbeart?

**Comment by cassiemc** [comment] 2015-03-02 19:49
Yes @edrushka, I can confirm – @iamjessklein you're the on-call engagement designer this week. Thanks for taking initiative here.

**Comment by iamjessklein** [comment] 2015-03-02 21:14
Hey @edrushka @HPaulJohnson @KevZawacki  - I posted two slightly different iterations of the mockup [here on redpen](https://redpen.io/p/xz3dcd0aa97ea663a1)

![nn1](https://cloud.githubusercontent.com/assets/535012/6450630/2ae893ec-c0f7-11e4-8821-e3e6ef2ae6b4.png)

![nn2](https://cloud.githubusercontent.com/assets/535012/6450636/3035d24c-c0f7-11e4-8db5-db63fa5586d4.PNG)

**Comment by edrushka** [comment] 2015-03-02 21:57
Nice! I prefer the first version, and I think the read more can just be a text link after the sentence - a button isn't necessary. @Melechuga @DaveSteer @valianttry

**Comment by KevZawacki** [comment] 2015-03-02 22:13
Looks great! No copy changes from my end.

**Comment by iamjessklein** [comment] 2015-03-03 14:52
Calling out this comment from @DaveSteer - and would like to touch base before I go forward with the next round of designs as the scope seems to have slightly been adjusted. 

"This section is giving too much prominence to something that people cannot take action on. Let’s create a 50-50 split. On the right, we can have the NN celebration/thank you. This should include image of #WonTheInternet, an embed of Mitchell’s video, a link to her blog. Would also be good to have an info-graphic with our stats.

On the left, let’s have ‘Take Action’ with the two actions: 1/See who’s watching you online and 2/Teach others about net neutrality."

**Comment by edrushka** [comment] 2015-03-03 17:07
+1 we should circle up. I'll book a short meeting @iamjessklein @DaveSteer

**Comment by cassiemc** [comment] 2015-03-03 17:27
@edrushka me too please!

**Comment by edrushka** [comment] 2015-03-03 18:27
@cassiemc @DaveSteer @iamjessklein @valianttry @Melechuga Let's meet after the advocacy team has a chance to circle up tomorrow to clarify who's project-managing this site.

**Comment by edrushka** [comment] 2015-03-04 22:02
@iamjessklein love your initiative with the alternative layouts in Redpen

This particular ticket was filed as (what I hoped would be) a quick update to remove the Call Congress and Sign the Petition CTA's that were no longer relevant when the NN campaign ended last week.

In April, the site will need more significant changes when the Open Web Fellows get announced. Here is the ticket in /plan: https://github.com/MozillaFoundation/plan/issues/370

Given that a restructuring of the advocacy site wasn't scoped for this heartbeat, I suggest we either:
a) remove and the Call Congress and Petition CTA buttons and replace with basic text and a link to Mitchell's blog (as I outlined above) and save the restructuring for the Open Web Fellows announcement, when it can be properly scoped and allocated through TPS.
b) not bother removing the Call Congress and Petition CTA buttons and simply make the next round of changes to the site with the Open Web Fellows announcement, when it can be properly scoped and allocated through TPS.

@valianttry is the decision maker here, so I'll let her give the final word. Andrea?

**Comment by cassiemc** [comment] 2015-03-05 00:51
+1 on decoupling the structural changes atm. I do think @iamjessklein's will be helpful in coming up with long-term templating solutions, so really nice work there Jess. Linking just for historical purposes (start here then move forward: https://redpen.io/ov9f35d39b5ecbe2ee )

**Comment by iamjessklein** [comment] 2015-03-05 13:05
+1 sounds good to me, mainly was concerned with carving out "promotional content" real estate on the site, which it sounds like is on everyone's minds.  Let me know what you decide on regarding this particular issue @valianttry @edrushka

**Comment by edrushka** [comment] 2015-03-05 17:02
@valianttry is now on PTO, returning March 16, so I'm going to close this issue. We can re-open if Andrea wants to move ahead in late March. Given that we need to update the site in early April for the Open Web Fellows announcement, she may opt to make this change then. I've moved @iamjessklein designs for structural changes to the Open Web Fellows announcement design ticket: https://github.com/MozillaFoundation/movement-building/issues/20

**Comment by edrushka** [comment] 2015-03-18 18:35
Re-opening. I'd like to remove the Call Congress and Petition CTA buttons and replace with basic text and a link to Mitchell's blog (as I outlined above) . @DaveSteer @valianttry please sign off so we can move this forward with a dev.

**Comment by DaveSteer** [comment] 2015-03-18 18:43
(Apologies - I had my Github email notifications incorrectly set and missed that we had closed this a few weeks ago. +1 for re-opening).

Approved to move forward, but can I see the latest version of the mockups? I remember commenting on them a few weeks ago and would love to see what we did as a result. Thanks.

Also - can we fix the button misalignment issue. See attached.
![screen shot 2015-03-18 at 10 14 06 am](https://cloud.githubusercontent.com/assets/9165845/6716628/0106172e-cd64-11e4-8827-72223b20ab77.png)

**Comment by edrushka** [comment] 2015-03-18 18:48
@DaveSteer you can view the mockup here: https://redpen.io/mj6366fbe60426efd6 I propose that we remove the button and add a simple 'Read More' text link at the end of the sentence that will point to Mitchell's blog.

**Comment by DaveSteer** [comment] 2015-03-18 19:06
My main concern is that it is too red-white-blue, which plays into the narrative that we are too focused on the U.S. Of course, this was a victory in U.S. policy, but the impact is global as other policy makers look to the U.S. Can we tone down the 'red'? Also, now that it's been 20+ days since the victory, it seems a bit too aligned to the vote. Are there other options that don't focus just on the win?

**Comment by edrushka** [comment] 2015-03-18 19:09
@DaveSteer let's circle up with @valianttry and come to a consensus on what you want, visually. Then we can finalize the design and pass off to a dev.

**Comment by iamjessklein** [comment] 2015-03-19 15:33
Perhaps the messaging shouldn't use the Net Neutrality "theme-ing" but be more aligned with the tone of the advocacy site. I wonder if there is a special ribbon or mark we could craft that signifies a victory. If we do that - then we could actually showcase several campaigns simultaneously in different states (victory, act now, time sensitive)

**Comment by edrushka** [comment] 2015-03-19 17:23
Oh nice idea, @iamjessklein! Love how you're thinking of long term design for the site! We're meeting Monday afternoon to sort out the content - I'll update this ticket as soon as we land.

**Comment by iamjessklein** [comment] 2015-03-19 22:29
:+1:  awesome

**Comment by edrushka** [comment] 2015-03-23 21:31
Ok, we got ourselves organized, @iamjessklein :)

Based off this redpen https://redpen.io/mj6366fbe60426efd6 please do the following:
1) change background to white
2) if the building needs a background coloured square, that's fine. Try to minimize the red/white/blue American vibe as much as possible.
3) Remove the Read More button. That should be a hyperlinked 'Read more' line of text at the end of the the paragraph.
4) Overall, this banner should take up less space vertically. Removing the Read More button should solve for that.
5) Align the buttons in the Take Action section.

^ This has all been agreed upon by myself, @valianttry and @DaveSteer. Thank you!!!

**Comment by edrushka** [comment] 2015-03-23 23:34
I filed this in /plan https://github.com/MozillaFoundation/plan/issues/399

**Closed as completed** 2015-04-24 21:29 UTC
Labels: needs-dev
