### ISSUE TITLE
Update the page for editing recurring donations; it's dated

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#24] opened 2015-03-25 18:12 UTC
We now have thousands of new monthly donors since EOY campaign, and we're getting a lot more hits to this page:
https://sendto.mozilla.org/page/recurring/find/

But as you can see it's about 30 versions old. We need to update this to current brand guidelines. 
![mozilla__donate](https://cloud.githubusercontent.com/assets/9830371/6831788/c6a7d582-d2df-11e4-8f3b-12ef92f96be2.png)

cc @edrushka

**Comment by edrushka** [comment] 2015-03-25 18:30
Ha! That’s so old it’s almost retro cool. If we leave it for 2 more years we’ll be ironic/cutting edge again ;)

TPS is sorting out how to address these misc tasks with no urgent deadline, so I'll make sure this gets labeled properly when the new system is in place.

**Comment by simonwex** [comment] 2015-03-26 00:10
@edrushka you'll actually have someone dedicated to helping you out next Heartbeat. Also, I believe you're right: http://www2.warnerbros.com/spacejam/movie/jam.htm

**Comment by alicoding** [comment] 2015-05-06 01:23
I'm trying to look for this page on BSD, but couldn't find it anywhere or perhaps my account is not fully accessible on all components. @ScottDowne do you know where this lives?

**Comment by ScottDowne** [comment] 2015-05-06 02:06
@alicoding Ah, this is not the ticket I thought it was.

I'm not able to find that page in BSD either. It is under `/recurring` which is new to me.

**Comment by alicoding** [comment] 2015-05-06 13:18
@valianttry can you help me get access to that page on BSD? I don't know if this is just me not knowing where exactly the page should be or I simply don't have permission to that page yet.

**Comment by alicoding** [comment] 2015-05-06 18:36
So, I've filed a ticket on BSD to find out about this page and apparently I don't have access to the page because of my permission level.

I also have a question since the page is not directly accessible by us in general. The guy over at BSD will be able to change the wrapper for us which means two things here in this case.
1. Create new wrapper for this page and ask them to change the wrapper to the new one.
2. Edit "Default wrapper" to newer design which then going to reflect every other pages that uses the default wrapper here.

Either we are going with number 1 or 2 I still need to come up with the new design which I'm not quite sure if we have a standard for it or anything in mind?

**Comment by valianttry** [comment] 2015-05-06 18:53
@alicoding I just gave you all permissions, use your power for good. :smile: 

@sabrinang and @mmmavis have dealt with wrappers in the past, I'm afraid I don't know the technical details of deploying a wrapper. Perhaps we can just choose a newer page wrapper we use for another purpose (such as donation form) and use that same code as our "default wrapper"? I'd ask them.

**Comment by alicoding** [comment] 2015-05-06 20:10
@valianttry I just synced up with Seth from BSD a bit to see if we can use our new/modern wrapper and this is what it will look like if we change it to the newer wrapepr.

![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/e4dzk9cr.png)

What do you think?

**Comment by valianttry** [comment] 2015-05-07 17:38
Looks SO MUCH BETTER! Is there any way to break that really long one-line "To make changes..." into 2 lines centered? The only other edit I would make if possible is to say "credit card" instead of just "card"

^ neither of these are blockers! If they're not editable by us just pull the trigger (as long as we test and make sure the page works. I can do that as I am a recurring donor).

Thanks @alicoding ! :clap:

**Comment by alicoding** [comment] 2015-05-07 18:35
I've just asked them to switch the wrapper and it should be up shortly then @valianttry you can test this to make sure if this is still working as expected :dancer: 

The only text I'm able to change is from `card` to `credit card` but I'm not able to make that to be two lines since I don't have access to the content directly.

**Comment by alicoding** [comment] 2015-05-07 18:51
@valianttry it is up! https://sendto.mozilla.org/page/recurring/find/ can you please test and close the ticket if it's all good? :)

**Comment by valianttry** [comment] 2015-05-07 20:01
I tested, all went well, except when I clicked on the "edit recurring" the form didn't come up:

![sendto_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/7524764/221038f6-f4b9-11e4-92ec-d0033f359716.png)

**Comment by alicoding** [comment] 2015-05-07 20:02
@valianttry ouch! Would it be possible if you can help me find out what's the error on the console there? or if you have time after the meeting to do a quick call to see that?

**Comment by valianttry** [comment] 2015-05-07 20:03
I know @ScottDowne is working on reformatting that form so maybe he has insight?

**Comment by ScottDowne** [comment] 2015-05-07 20:27
@alicoding @valianttry Yeah, that's totally my bug: https://github.com/MozillaFoundation/movement-building/issues/23

Now that ali has context I'll lean off him for review.

:)

**Comment by edrushka** [comment] 2015-05-11 21:33
Scott is mega booked this heartbeat, so this is going to have to go on pause for a bit.

**Comment by ScottDowne** [comment] 2015-05-11 21:39
Ohh, forgot about this.

I totally shipped the updated edit form Friday.

Ali shipped the initial form too.

Closing this.

**Closed as completed by ScottDowne** 2015-05-11 21:39 UTC
Labels: needs-dev

**Comment by edrushka** [comment] 2015-05-11 21:42
@alicoding can you test your form for the "edit reoccurring" issue and close this if fixed?

**Comment by ScottDowne** [comment] 2015-05-11 21:43
@edrushka already confirmed and closed :)

**Comment by edrushka** [comment] 2015-05-11 21:51
:dancers::dancers::dancers:
